src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java, src/main/java/seedu/duke/User.java
add view timetable function. Now can enter "view" to see the timetable of the current active user.
=> Add viewTimetable function

build.gradle, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/InvalidDayException.java, src/main/java/seedu/duke/InvalidFormatException.java, src/main/java/seedu/duke/InvalidUserException.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java, src/main/java/seedu/duke/User.java, src/main/java/seedu/duke/UserList.java, src/main/java/seedu/duke/ui/UI.java, src/test/java/seedu/duke/DukeTest.java, src/test/java/seedu/duke/TimetableTest.java
Added Parsing functionality resulting in a less cluttered main class.
Completed Timetable comparison functionality.
Changed structure of classes such as UserList and Timetable (Hashmap implementation)
Added extensive error handling for all current commands.
=> John's v1.0 changes

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Task.java, src/test/java/seedu/duke/DukeTest.java
allow user inputs of time in the format of both "9:00" and "09:00"
=> Allow user inputs of time of both 1 and 2 digits

docs/UserGuide.md, src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java, src/main/java/seedu/duke/User.java, src/main/java/seedu/duke/UserList.java, src/main/java/seedu/duke/ui/UI.java, src/test/java/seedu/duke/DukeTest.java, src/test/java/seedu/duke/TimetableTest.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
Clean up code. add help command
=> Clean up code. add help command

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java, src/test/java/seedu/duke/DukeTest.java, src/test/java/seedu/duke/TimetableTest.java
add another parameter called flexibility to the task type such that we can tell the task is compulsory or flexible.
=> Add flexibility to the task

src/main/java/seedu/duke/InputValidator.java
clean up the line more than 120 characters
=> Solve line too long problem

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java
due to the added parameter in task class, i changed the addtask method in timetable class
=> change timetable add task method 

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java
We can change the timing for the task if its type is flexible
=> Add method to change timing of flexible task

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/Timetable.java
We can change the type of the task such that user would not need to delete and add task again
=> Add method of change type of tasks

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/ui/UI.java
1. Add addTaskForAll function to add a confirmed event to all users' timetable
2. Refactor parseTask method to make it reusable
3. add ui to print the added common event
=> Add addTaskForAll function

src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java
Show confirmed common events for all users
=> Add show confirmed events method

src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Task.java
add assertions to prevent users from assessing the timtable before adding a user
=> Add assertions

src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Timetable.java, src/main/java/seedu/duke/ui/UI.java, text-ui-test/input.txt
=> Add compare all

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Timetable.java
this is so that the user will not tediously add repeated task one by one, can be done in this method.
=> Add addRepeatTask function

src/test/java/seedu/duke/InputValidatorTest.java, src/test/java/seedu/duke/TimetableTest.java
=> Add Junit test to timetable class and inputInvalidator test

src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Timetable.java
solve some issues as well, like one command calling 2 methods
=> Add assert into te changeFlexibleTaskTiming

src/main/java/seedu/duke/Duke.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Storage.java, src/main/java/seedu/duke/Task.java, src/main/java/seedu/duke/User.java, src/main/java/seedu/duke/ui/UI.java
Add storage class such that: 
1. when the app opens the first time, a folder named "data" will be created.
2. When a new user is added, a file named after the new user is created in the folder.
3. The tasks will be written into the corresponding file. 
4. When reopening the app, it will first add all the existing users to userList and load data for each user.
=> Add Storage class and functions

docs/UserGuide.md
=> Wenqing checkclash

src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Timetable.java
previously we did not pass some gradle checks, so i change some lines
=> clean up code on indentation error

src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Storage.java, src/main/java/seedu/duke/Timetable.java, src/main/java/seedu/duke/User.java, src/test/java/seedu/duke/ParserTest.java
Fixed issue: [PE-D][Tester C] Exception message is not self-generated; clean up code
=> Fixed issue: [PE-D][Tester C] Exception message is not self-generated

docs/UserGuide.md, src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Storage.java, src/test/java/seedu/duke/StorageTest.java
1. print no common events when there is no common events.
2. fix user guide
=> Fix addforall bugs

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/ui/UI.java, src/test/java/seedu/duke/ParserTest.java
Fixed issue: [PE-D][Tester D] Inputting correct user for compare command does not leads to an error
=> Fixed issue: [PE-D][Tester D] Inputting correct user for compare command does not leads to an error

src/main/java/seedu/duke/Parser.java
Fixed issue: [PE-D][Tester C] addrepeattask does not support upper case inputs for day
=> Fixed issue: [PE-D][Tester C] addrepeattask does not support upper case inputs for day

src/main/java/seedu/duke/Parser.java
now there will be 2 exceptions which are invalid format and days exception
=> Add a new exception such that less than 2 input days will be detected

src/main/java/seedu/duke/Parser.java
an error message is printed if additional text behind "todaytask" command.
=> solve issue on todaytask

src/main/java/seedu/duke/InputValidator.java, src/main/java/seedu/duke/Main.java, src/main/java/seedu/duke/Parser.java, src/main/java/seedu/duke/Storage.java
allow users to add a certain task to users mentioned, thus allow users to add task for multiple users at the same time.
=> Add addfor method

src/main/java/seedu/duke/Parser.java, src/test/java/seedu/duke/ParserTest.java
Fixed issue where the same user can be readded
=> Fixed issue where the same user can be readded

docs/team/john-nng.md, src/main/java/seedu/duke/InputValidator.java, src/test/java/seedu/duke/InputValidatorTest.java
More testing for functions in InputValidatorTest such as 
- Addtask
- Deletetask
- Compare
- Compareall
- AddUser
=> John PPP and More Testing for InputValidator

docs/team/Leong-ZM.md
=> Add Leong-ZM PPP

docs/DeveloperGuide.md, docs/README.md, docs/team/johndoe.md
=> Clean up template

src/main/java/seedu/duke/ui/UI.java
=> Update help command

src/main/java/seedu/duke/Parser.java
ignores cases for days for addfor function
=> Fix DAYS error
